# Generated by Django 5.0.6 on 2024-05-25 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_responsables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='carreras',
            new_name='Carrera',
        ),
        migrations.RenameModel(
            old_name='Responsables',
            new_name='Responsable',
        ),
    ]
