# Generated by Django 5.0.6 on 2024-06-08 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Observacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.responsable'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion'),
        ),
    ]
