# Generated by Django 5.0.6 on 2024-06-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_inventario_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Carrera',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Observacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Responsable',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Ubicacion',
            field=models.CharField(max_length=50),
        ),
    ]
